name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  create-new-branch:

    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Touch Framework
      run: npm install touch-cli -g
    - name: Create feature branch
      run: git checkout -b feature/engine_upgrade
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        touch initial
        git add initial
        git commit --m "Prepare release"
        git push --set-upstream origin feature/engine_upgrade
    - name: Push new branch
      run: git push
