name: Deploy To Lambda

on:
  push:
    branches: [ "master" ]
env:
  USER_NAME: Shubham is running this action.

jobs:
  
  configure-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::407672363742:role/service-role/TestLambdaCD-role-365n8lqu
          aws-region: us-east-1