name: Deploy To Lambda

on:
  push:
    branches: [ "master" ]
env:
  USER_NAME: Shubham is running this action.
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  
  configure-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:sts::407672363742:assumed-role/LabAdmin/SJAIN2
          aws-region: us-east-1